<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Patient>
 */
class DonorFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        $cities = [
            'Kathmandu, Kathmandu, Province 3',
            'Pokhara, Kaski, Gandaki Pradesh',
            'Lalitpur, Lalitpur, Bagmati Pradesh',
            'Bhaktapur, Bhaktapur, Bagmati Pradesh',
            'Nepalgunj, Banke, Bheri Pradesh',
            'Dharan, Sunsari, Koshi Pradesh',
            'Biratnagar, Morang, Koshi Pradesh',
            'Janakpur, Dhanusa, Janakpur Pradesh',
            'Birgunj, Parsa, Narayani Pradesh',
            'Butwal, Rupandehi, Lumbini Pradesh',
            'Tansen, Palpa, Lumbini Pradesh',
            'Tulsipur, Dang Deokhuri, Rapti Pradesh',
            'Dhangadhi, Kailali, Sudurpashchim Pradesh',
            'Gaur, Rautahat, Narayani Pradesh',
            'Hetauda, Makwanpur, Bagmati Pradesh',
            'Ilam, Ilam, Mechi Pradesh',
            'Jumla, Jumla, Karnali Pradesh',
            'Kailali, Kailali, Sudurpashchim Pradesh',
            'Kalaiya, Bara, Narayani Pradesh',
            'Kanchanpur, Kanchanpur, Sudurpashchim Pradesh',
            'Kapilvastu, Kapilvastu, Lumbini Pradesh',
            'Lahan, Siraha, Sagarmatha Pradesh',
            'Lamahi, Dang Deokhuri, Rapti Pradesh',
            'Madhyapur Thimi, Bhaktapur, Bagmati Pradesh',
            'Mahendranagar, Dhanusa, Janakpur Pradesh',
            'Mechinagar, Jhapa, Mechi Pradesh',
            'Narayangarh, Chitwan, Bagmati Pradesh',
            'Nawalparasi, Nawalparasi, Lumbini Pradesh',
            'Parasi, Nawalparasi, Lumbini Pradesh',
            'Rajbiraj, Saptari, Sagarmatha Pradesh',
            'Rupandehi, Rupandehi, Lumbini Pradesh',
            'Salyan, Salyan, Karnali Pradesh',
            'Siddharthanagar, Bara, Narayani Pradesh',
            'Siraha, Siraha, Sagarmatha Pradesh',
            'Tikapur, Kailali, Sudurpashchim Pradesh',
            'Tulsipur, Dang Deokhuri, Rapti Pradesh',
            'Dhangadhi, Kailali, Sudurpashchim Pradesh',
            'Gaur, Rautahat, Narayani Pradesh',
            'Hetauda, Makwanpur, Bagmati Pradesh',
            'Ilam, Ilam, Mechi Pradesh',
            'Jumla, Jumla, Karnali Pradesh',
            'Kailali, Kailali, Sudurpashchim Pradesh',
            'Kalaiya, Bara, Narayani Pradesh',
            'Kanchanpur, Kanchanpur, Sudurpashchim Pradesh'
        ];

        $names = [
            "Prabesh Shrestha",
            "Sabin Karki",
            "Binita Thapa",
            "Nisha Shah",
            "Rabin Shrestha",
            "Krishna Gurung",
            "Sabita Sharma",
            "Dipesh Nepal",
            "Sagar Khatri",
            "Sunita Dhakal",
            "Anil Maharjan",
            "Bikram Adhikari",
            "Chandra Gurung",
            "Dipendra Shrestha",
            "Ekta Bhandari",
            "Gita Karki",
            "Jeevan Bhandari",
            "Kiran Shrestha",
            "Lalita Adhikari",
            "Mani Gurung",
            "Nabin Shrestha",
            "Purna Maharjan",
            "Ram Krishna Shrestha",
            "Santosh Thapa",
            "Shiva Prasad Sharma",
            "Sita Thapa",
            "Usha Bhandari",
            "Yogendra Gurung",
            "Amit Shrestha",
            "Binod Karki",
            "Chandra Khatri",
            "Diwakar Bhandari",
            "Ganesh Gurung",
            "Jaya Bhandari",
            "Keshav Shrestha",
            "Laxmi Adhikari",
            "Madhav Karki",
            "Nabin Maharjan",
            "Pramod Gurung",
            "Ramesh Adhikari",
            "Sarita Khatri",
            "Shiva Gurung",
            "Sunil Shrestha",
            "Uttam Maharjan",
            "Yogesh Bhandari",
            "Amar Shrestha",
            "Bikash Adhikari",
            "Chandra Bhandari",
            "Dipendra Karki",
            "Gita Maharjan",
            "Jeevan Shrestha",
            "Kiran Gurung",
            "Laxmi Thapa",
            "Mani Bhandari",
            "Nabin Adhikari",
            "Purna Khatri",
            "Ram Krishna Gurung",
            "Santosh Shrestha",
            "Shiva Prasad Karki",
            "Sita Adhikari",
            "Usha Thapa",
            "Yogendra Bhandari",
            "Amit Adhikari",
            "Binod Bhandari",
            "Chandra Gurung",
            "Diwakar Karki",
            "Ganesh Maharjan",
            "Jaya Thapa",
            "Keshav Gurung",
            "Laxmi Khatri",
            "Madhav Bhandari",
            "Nabin Gurung",
            "Pramod Shrestha",
            "Ramesh Karki",
            "Sarita Maharjan",
            "Shiva Gurung",
            "Sunil Adhikari",
            "Uttam Bhandari",
            "Yogesh Kandel"
        ];          

        return [
            'name' => fake()->randomElement($names),
            'blood_group' => fake()->randomElement(['A+', 'B+', 'O+', 'AB+', 'A-', 'B-', 'O-', 'AB-']),
            'contact' => fake()->unique()->numberBetween(9800000000, 9899999999),
            'address' => fake()->randomElement($cities),
            'age' => fake()->numberBetween(16, 60),
            'gender' => fake()->randomElement(['male', 'female']),
            'donation_interval' => fake()->randomElement(['3 months', '6 months', '1 year', 'irregular']),
            'last_donation_at' => fake()->dateTimeBetween('-3 years', 'now'),
            'description' => fake()->realText(300),
        ];
    }
}
